service: nestjs-serverless-starter
frameworkVersion: '3'

#useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stackTags:
    Owner: 'Massimo Biagioli'
    Destroy: 'false'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  app:
    handler: src/lambda.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{any+}
          method: ANY
